
service: number-facts

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ACCOUNT_SID: ${file(./config.yml):ACCOUNT_SID}
    ACCOUNT_TOKEN: ${file(./config.yml):ACCOUNT_TOKEN}
    FROM_NUMBER: ${file(./config.yml):FROM_NUMBER}
    FACT_API: ${file(./config.yml):FACT_API}

functions:
  send:
    handler: handler.run
    events:
      - schedule: cron(0 12 * * ? *)
